// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback _Nonnull free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureResultU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureResultI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureResultU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureResultI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureResultU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureResultI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureResultU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureResultI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureResultF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureResultF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureResultRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureResultVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_LISTENER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_LISTENER_METHOD0
typedef void (*UniffiCallbackInterfaceEventListenerMethod0)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EVENT_LISTENER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EVENT_LISTENER
typedef struct UniffiVTableCallbackInterfaceEventListener {
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
    UniffiCallbackInterfaceClone _Nonnull uniffiClone;
    UniffiCallbackInterfaceEventListenerMethod0 _Nonnull onEvent;
} UniffiVTableCallbackInterfaceEventListener;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_CLONE_EVENTLISTENER
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_CLONE_EVENTLISTENER
uint64_t uniffi_himffi_fn_clone_eventlistener(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_FREE_EVENTLISTENER
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_FREE_EVENTLISTENER
void uniffi_himffi_fn_free_eventlistener(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_INIT_CALLBACK_VTABLE_EVENTLISTENER
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_INIT_CALLBACK_VTABLE_EVENTLISTENER
void uniffi_himffi_fn_init_callback_vtable_eventlistener(const UniffiVTableCallbackInterfaceEventListener* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_EVENTLISTENER_ON_EVENT
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_EVENTLISTENER_ON_EVENT
void uniffi_himffi_fn_method_eventlistener_on_event(uint64_t ptr, RustBuffer event, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_CLONE_SESSION
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_CLONE_SESSION
uint64_t uniffi_himffi_fn_clone_session(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_FREE_SESSION
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_FREE_SESSION
void uniffi_himffi_fn_free_session(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_ACK
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_ACK
void uniffi_himffi_fn_method_session_ack(uint64_t ptr, RustBuffer guid, RustBuffer from, RustBuffer kind, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_ADD_FRIEND
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_ADD_FRIEND
uint64_t uniffi_himffi_fn_method_session_add_friend(uint64_t ptr, RustBuffer login, RustBuffer note
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_AGREE
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_AGREE
uint64_t uniffi_himffi_fn_method_session_agree(uint64_t ptr, RustBuffer nickname, uint16_t icon
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_AGREE_NOWAIT
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_AGREE_NOWAIT
void uniffi_himffi_fn_method_session_agree_nowait(uint64_t ptr, RustBuffer nickname, uint16_t icon, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_BLOCK
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_BLOCK
uint64_t uniffi_himffi_fn_method_session_block(uint64_t ptr, RustBuffer login
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_DISCONNECT
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_DISCONNECT
void uniffi_himffi_fn_method_session_disconnect(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_DOWNLOAD_MEDIA
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_DOWNLOAD_MEDIA
uint64_t uniffi_himffi_fn_method_session_download_media(uint64_t ptr, RustBuffer id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_FIND_USER
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_FIND_USER
uint64_t uniffi_himffi_fn_method_session_find_user(uint64_t ptr, RustBuffer login
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_GET_BUDDY_ICON
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_GET_BUDDY_ICON
uint64_t uniffi_himffi_fn_method_session_get_buddy_icon(uint64_t ptr, RustBuffer login
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_GET_INFO
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_GET_INFO
uint64_t uniffi_himffi_fn_method_session_get_info(uint64_t ptr, RustBuffer login
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_GET_ROSTER
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_GET_ROSTER
uint64_t uniffi_himffi_fn_method_session_get_roster(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_GET_USERS
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_GET_USERS
uint64_t uniffi_himffi_fn_method_session_get_users(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_GIF_ICON
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_GIF_ICON
uint64_t uniffi_himffi_fn_method_session_gif_icon(uint64_t ptr, uint16_t user_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_GIF_ICONS
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_GIF_ICONS
uint64_t uniffi_himffi_fn_method_session_gif_icons(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_HAS_BUDDY_ICONS
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_HAS_BUDDY_ICONS
int8_t uniffi_himffi_fn_method_session_has_buddy_icons(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_INFO
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_INFO
RustBuffer uniffi_himffi_fn_method_session_info(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_IS_OPEN
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_IS_OPEN
int8_t uniffi_himffi_fn_method_session_is_open(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_REMOVE_FRIEND
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_REMOVE_FRIEND
uint64_t uniffi_himffi_fn_method_session_remove_friend(uint64_t ptr, RustBuffer login
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_RESPOND
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_RESPOND
uint64_t uniffi_himffi_fn_method_session_respond(uint64_t ptr, RustBuffer login, int8_t accept
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_SEARCH
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_SEARCH
uint64_t uniffi_himffi_fn_method_session_search(uint64_t ptr, RustBuffer query
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_SEND_CHAT
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_SEND_CHAT
void uniffi_himffi_fn_method_session_send_chat(uint64_t ptr, RustBuffer text, int8_t emote, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_SEND_CHAT_MEDIA
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_SEND_CHAT_MEDIA
void uniffi_himffi_fn_method_session_send_chat_media(uint64_t ptr, RustBuffer text, RustBuffer media, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_SEND_IM
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_SEND_IM
uint64_t uniffi_himffi_fn_method_session_send_im(uint64_t ptr, RustBuffer to, RustBuffer guid, RustBuffer body
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_SEND_PRIVATE
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_SEND_PRIVATE
uint64_t uniffi_himffi_fn_method_session_send_private(uint64_t ptr, uint16_t user_id, RustBuffer text, RustBuffer media
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_SET_ALIAS
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_SET_ALIAS
uint64_t uniffi_himffi_fn_method_session_set_alias(uint64_t ptr, RustBuffer login, RustBuffer alias
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_SET_BUDDY_ICON
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_SET_BUDDY_ICON
uint64_t uniffi_himffi_fn_method_session_set_buddy_icon(uint64_t ptr, RustBuffer picture
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_SET_GIF_ICON
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_SET_GIF_ICON
uint64_t uniffi_himffi_fn_method_session_set_gif_icon(uint64_t ptr, RustBuffer gif
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_SET_INFO
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_SET_INFO
uint64_t uniffi_himffi_fn_method_session_set_info(uint64_t ptr, RustBuffer profile
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_SET_PRESENCE
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_SET_PRESENCE
uint64_t uniffi_himffi_fn_method_session_set_presence(uint64_t ptr, RustBuffer presence, RustBuffer status, RustBuffer discoverable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_TYPING
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_TYPING
void uniffi_himffi_fn_method_session_typing(uint64_t ptr, RustBuffer to, int8_t typing, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_UNBLOCK
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_UNBLOCK
uint64_t uniffi_himffi_fn_method_session_unblock(uint64_t ptr, RustBuffer login
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_UPLOAD_MEDIA
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_METHOD_SESSION_UPLOAD_MEDIA
uint64_t uniffi_himffi_fn_method_session_upload_media(uint64_t ptr, RustBuffer data
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_FUNC_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_FUNC_CONNECT
uint64_t uniffi_himffi_fn_func_connect(RustBuffer sign_on, uint64_t listener
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_FUNC_DEFAULT_TRACKERS
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_FUNC_DEFAULT_TRACKERS
RustBuffer uniffi_himffi_fn_func_default_trackers(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_FUNC_EMOJI_TO_FACES
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_FUNC_EMOJI_TO_FACES
RustBuffer uniffi_himffi_fn_func_emoji_to_faces(RustBuffer text, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_FUNC_FACES_TO_EMOJI
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_FUNC_FACES_TO_EMOJI
RustBuffer uniffi_himffi_fn_func_faces_to_emoji(RustBuffer text, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_FUNC_ICON_HASH
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_FUNC_ICON_HASH
RustBuffer uniffi_himffi_fn_func_icon_hash(RustBuffer data, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_FUNC_INSPECT_ICON
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_FUNC_INSPECT_ICON
RustBuffer uniffi_himffi_fn_func_inspect_icon(RustBuffer data, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_FUNC_LIST_SERVERS
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_FUNC_LIST_SERVERS
uint64_t uniffi_himffi_fn_func_list_servers(RustBuffer trackers, uint32_t timeout_secs
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_FUNC_NEW_GUID
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_FN_FUNC_NEW_GUID
RustBuffer uniffi_himffi_fn_func_new_guid(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUSTBUFFER_ALLOC
RustBuffer ffi_himffi_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_himffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUSTBUFFER_FREE
void ffi_himffi_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUSTBUFFER_RESERVE
RustBuffer ffi_himffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_POLL_U8
void ffi_himffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_CANCEL_U8
void ffi_himffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_FREE_U8
void ffi_himffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_himffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_POLL_I8
void ffi_himffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_CANCEL_I8
void ffi_himffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_FREE_I8
void ffi_himffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_himffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_POLL_U16
void ffi_himffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_CANCEL_U16
void ffi_himffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_FREE_U16
void ffi_himffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_himffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_POLL_I16
void ffi_himffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_CANCEL_I16
void ffi_himffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_FREE_I16
void ffi_himffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_himffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_POLL_U32
void ffi_himffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_CANCEL_U32
void ffi_himffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_FREE_U32
void ffi_himffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_himffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_POLL_I32
void ffi_himffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_CANCEL_I32
void ffi_himffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_FREE_I32
void ffi_himffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_himffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_POLL_U64
void ffi_himffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_CANCEL_U64
void ffi_himffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_FREE_U64
void ffi_himffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_himffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_POLL_I64
void ffi_himffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_CANCEL_I64
void ffi_himffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_FREE_I64
void ffi_himffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_himffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_POLL_F32
void ffi_himffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_CANCEL_F32
void ffi_himffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_FREE_F32
void ffi_himffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_COMPLETE_F32
float ffi_himffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_POLL_F64
void ffi_himffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_CANCEL_F64
void ffi_himffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_FREE_F64
void ffi_himffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_COMPLETE_F64
double ffi_himffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_himffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_himffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_himffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_himffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_POLL_VOID
void ffi_himffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_CANCEL_VOID
void ffi_himffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_FREE_VOID
void ffi_himffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_HIMFFI_RUST_FUTURE_COMPLETE_VOID
void ffi_himffi_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_FUNC_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_FUNC_CONNECT
uint16_t uniffi_himffi_checksum_func_connect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_FUNC_DEFAULT_TRACKERS
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_FUNC_DEFAULT_TRACKERS
uint16_t uniffi_himffi_checksum_func_default_trackers(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_FUNC_EMOJI_TO_FACES
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_FUNC_EMOJI_TO_FACES
uint16_t uniffi_himffi_checksum_func_emoji_to_faces(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_FUNC_FACES_TO_EMOJI
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_FUNC_FACES_TO_EMOJI
uint16_t uniffi_himffi_checksum_func_faces_to_emoji(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_FUNC_ICON_HASH
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_FUNC_ICON_HASH
uint16_t uniffi_himffi_checksum_func_icon_hash(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_FUNC_INSPECT_ICON
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_FUNC_INSPECT_ICON
uint16_t uniffi_himffi_checksum_func_inspect_icon(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_FUNC_LIST_SERVERS
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_FUNC_LIST_SERVERS
uint16_t uniffi_himffi_checksum_func_list_servers(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_FUNC_NEW_GUID
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_FUNC_NEW_GUID
uint16_t uniffi_himffi_checksum_func_new_guid(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_EVENTLISTENER_ON_EVENT
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_EVENTLISTENER_ON_EVENT
uint16_t uniffi_himffi_checksum_method_eventlistener_on_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_ACK
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_ACK
uint16_t uniffi_himffi_checksum_method_session_ack(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_ADD_FRIEND
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_ADD_FRIEND
uint16_t uniffi_himffi_checksum_method_session_add_friend(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_AGREE
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_AGREE
uint16_t uniffi_himffi_checksum_method_session_agree(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_AGREE_NOWAIT
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_AGREE_NOWAIT
uint16_t uniffi_himffi_checksum_method_session_agree_nowait(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_BLOCK
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_BLOCK
uint16_t uniffi_himffi_checksum_method_session_block(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_DISCONNECT
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_DISCONNECT
uint16_t uniffi_himffi_checksum_method_session_disconnect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_DOWNLOAD_MEDIA
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_DOWNLOAD_MEDIA
uint16_t uniffi_himffi_checksum_method_session_download_media(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_FIND_USER
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_FIND_USER
uint16_t uniffi_himffi_checksum_method_session_find_user(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_GET_BUDDY_ICON
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_GET_BUDDY_ICON
uint16_t uniffi_himffi_checksum_method_session_get_buddy_icon(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_GET_INFO
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_GET_INFO
uint16_t uniffi_himffi_checksum_method_session_get_info(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_GET_ROSTER
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_GET_ROSTER
uint16_t uniffi_himffi_checksum_method_session_get_roster(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_GET_USERS
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_GET_USERS
uint16_t uniffi_himffi_checksum_method_session_get_users(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_GIF_ICON
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_GIF_ICON
uint16_t uniffi_himffi_checksum_method_session_gif_icon(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_GIF_ICONS
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_GIF_ICONS
uint16_t uniffi_himffi_checksum_method_session_gif_icons(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_HAS_BUDDY_ICONS
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_HAS_BUDDY_ICONS
uint16_t uniffi_himffi_checksum_method_session_has_buddy_icons(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_INFO
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_INFO
uint16_t uniffi_himffi_checksum_method_session_info(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_IS_OPEN
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_IS_OPEN
uint16_t uniffi_himffi_checksum_method_session_is_open(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_REMOVE_FRIEND
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_REMOVE_FRIEND
uint16_t uniffi_himffi_checksum_method_session_remove_friend(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_RESPOND
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_RESPOND
uint16_t uniffi_himffi_checksum_method_session_respond(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_SEARCH
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_SEARCH
uint16_t uniffi_himffi_checksum_method_session_search(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_SEND_CHAT
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_SEND_CHAT
uint16_t uniffi_himffi_checksum_method_session_send_chat(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_SEND_CHAT_MEDIA
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_SEND_CHAT_MEDIA
uint16_t uniffi_himffi_checksum_method_session_send_chat_media(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_SEND_IM
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_SEND_IM
uint16_t uniffi_himffi_checksum_method_session_send_im(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_SEND_PRIVATE
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_SEND_PRIVATE
uint16_t uniffi_himffi_checksum_method_session_send_private(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_SET_ALIAS
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_SET_ALIAS
uint16_t uniffi_himffi_checksum_method_session_set_alias(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_SET_BUDDY_ICON
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_SET_BUDDY_ICON
uint16_t uniffi_himffi_checksum_method_session_set_buddy_icon(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_SET_GIF_ICON
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_SET_GIF_ICON
uint16_t uniffi_himffi_checksum_method_session_set_gif_icon(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_SET_INFO
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_SET_INFO
uint16_t uniffi_himffi_checksum_method_session_set_info(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_SET_PRESENCE
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_SET_PRESENCE
uint16_t uniffi_himffi_checksum_method_session_set_presence(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_TYPING
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_TYPING
uint16_t uniffi_himffi_checksum_method_session_typing(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_UNBLOCK
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_UNBLOCK
uint16_t uniffi_himffi_checksum_method_session_unblock(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_UPLOAD_MEDIA
#define UNIFFI_FFIDEF_UNIFFI_HIMFFI_CHECKSUM_METHOD_SESSION_UPLOAD_MEDIA
uint16_t uniffi_himffi_checksum_method_session_upload_media(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_HIMFFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_HIMFFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_himffi_uniffi_contract_version(void
    
);
#endif

